import Link from 'next/link'
import './globals.css'
import {ReactNode} from 'react';
import {Metadata} from "next";
import {Control} from "@/app/control";

interface RootLayoutProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: 'WEB tutorial',
    description: 'Generated by egoing',
}

export default async function RootLayout({children}: RootLayoutProps) {
    // 캐시 사용 안함
    const resp: Response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics/`, {cache:'no-cache'})
    //const resp: Response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics/`)
    const topics: [any] = await resp.json();
    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            {topics.map(topic => {
                return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })}
        </ol>
        {children}
        <Control/>
        </body>
        </html>
    )
}